### ISSUE TITLE
Import Collective Actors

### ISSUE THREAD

**Issue by gaetanmuck** [geovistory/symogih#10]
## Importation des acteurs collectifs
- E74 Group
- Dans projet 6857901

### Types BHP

- On importe uniquement les CoAc de type 1051 (Collectivité structurée), 1052 (Collectivité informelle) et type vide.

### Association à un projet

- https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#association-%C3%A0-un-projet

Associer tous les acteurs collectifs et leurs informations liées ainsi :

| pk projet symogih | Nom projet symogih | pk projet GV | Nom projet GV |
| -------------------------- | ------------------------------ | ------------------ | --------------------- |
|                                  | Tous les acteurs collectifs | 6857901 | symogih |
| 14841                      | Siprojuris | 7918384 | Siprojuris |
| 14841                      | Siprojuris | 1483135 | Academic Education & Careers (Community Project) |
| 14698                      | Monastica | 801348 | Monastica |
| 15789                     | Établissements d'enseignement technique | 8381499 | Établissements d'enseignement technique |
| 12782                     | Scholasticon | 8989741 | Scholasticon |
| 12782                     | Scholasticon |  373987  | Espace intellectuel |

### Créateur
- admin_users.login [actor.creator = admin_users.pk_user]

### Modificateur
- admin_users.login [actor.modifier = admin_users.pk_user]

### Appellations

- cf. Semantic-Data-for-Humanities/Alignement_symogih.org#161
- Noms des acteurs : collective_actor_name.name
- Type du nom : https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#type-de-nom
- Temporalité : https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#temporalit%C3%A9-des-noms
- Langue : actor_name.lang_iso [défaut fra]

#### Appellations favorites

- Mettre en favori l’appellation qui correspond au nom standard : https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#nom-standard

### URI
- symogih.org/resource/ActrXXX

### Notices textes
- https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#notices-texte

### Date de formation du groupe
- On crée une TeEn E66 Formation toutes les fois qu'on a soit une information TyIn30 Création d'un acteur collectif soit une année de création dans collective_actor.begin_year
- /!\ Il ne peut y avoir qu'un seul et unique événement de création repéré par le type de rôle 49 "être créé".
- Pour trouver le TyIn30 :
   - collective_actor.concat_coac = information_role.fk_associated_object
   - information_role.fk_type_role = 49
   - information_role.fk_information = information.pk_information
   - information.fk_type_information = 30
- Si information création, date de E66 Formation : information.pk_information = information_date.fk_information
  - sameAs URI : http://symogih.org/resource/InfoXXX [XXX = pk_information]
- Si pas d'information création mais une année de création, créer une TeEn E66 Formation avec date collective_actor.begin_year

### Date de dissolution du groupe
- On crée une TeEn E68 Dissolution toutes les fois qu'on a soit une information TyIn33 Fin d'existence d'un acteur collectif soit une année de fin dans collective_actor.end_year
- /!\ Il ne peut y avoir qu'un seul et unique événement de dissolution repéré par le type de rôle 54 "disparaître".
- Pour trouver le TyIn33 :
   - collective_actor.concat_coac = information_role.fk_associated_object
   - information_role.fk_type_role = 54
   - information_role.fk_information = information.pk_information
   - information.fk_type_information = 33
- Si information création, date de E68 Dissolution : information.pk_information = information_date.fk_information
  - sameAs URI : http://symogih.org/resource/InfoXXX [XXX = pk_information] 
- Si pas d'information fin d'existence mais une année de fin, créer une TeEn E68 Dissolution avec date collective_actor.end_year

**ATTENTION** : les TeEn E66 et E68 et leurs propriétés ne sont pas encore disponibles dans un profil de GV, voir avec @stephenhart8 

#### Type de date
- https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#type-de-date

#### Indication de fiabilité
- https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#indication-de-fiabilit%C3%A9

#### Compléments et notes
- https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#compl%C3%A9ments-et-notes

#### Propriétés à utiliser pour les CoAc sans Formation et/ou Dissolution
- https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#qualification-des-dates-dun-peit

### Notices d'autorité
- https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#notices-dautorit%C3%A9

**Comment by valamercery** [comment]
*   On importe uniquement les CoAc de type 1051 (Collectivité structurée), 1052 (Collectivité informelle) et type vide.
*   Ces CoAc ne sont pas typés dans GV, ils sont tous créés comme instances de E74 Group.
*   La colonne name\_type est obsolète dans toutes les tables, elle a été remplacée par abob\_XX\_name\_type.

**Comment by gaetanmuck** [comment]
- Si il y a des dates dans les noms, ont mets bien les propriétés `end of the begin` pour le début et `begin of the end` pour la fin?

**Comment by atterebf** [comment]
ATTENTION: les TyRo n'ont pas été pris en compte.

Pour trouver le TyIn30 :

*   collective\_actor.concat\_coac = information\_role.fk\_associated\_object
*   information\_role.fk\_type\_role = 49
*   information\_role.fk\_information = information.pk\_information
*   information.fk\_type\_information = 30

Par conséquent il y a plein de créations en trop !
