### ISSUE TITLE
BHP Import : Association des données au projet Sippaf

### ISSUE THREAD

**Issue by valamercery** [geovistory/symogih#16]
Associer au projet Sippaf tous les :

* Actr Acteurs / E21 Person
* CoAc Acteurs collectifs / E74 Group
* NaPl Lieu / C13 Geographical Place
* Leurs informations / TeEn liées (Birth, Death, Formation, Dissolution, etc.)
* Les liens entre les TeEn et les Geographical Place

| pk projet symogih | Nom projet symogih | pk projet GV | Nom projet GV |
| -------------------------- | ------------------------------ | ------------------ | --------------------- |
| 12781                      | Sippaf | 11033927 | Sippaf |

Doc : https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#association-%C3%A0-un-projet

**Comment by gaetanmuck** [comment]
Pour le transfert dans un projet, nous avions l'habitude de nous fier uniquement sur l'association au projet dans la BHP (de toutes les entités, plus leur graph associé), est ce que cette technique regroupera bien la liste des classes mentionnées dans ce ticket?

**Comment by valamercery** [comment]
Oui je pense, il faut appliquer la même méthode que pour l'association des entités à Siprojuris ou Établissements par exemple.

**Comment by gaetanmuck** [comment]
Ok ça marche, je fais le transfert ce soir.
