### ISSUE TITLE
Import actors - Fields

### ISSUE THREAD

**Issue by valamercery** [geovistory/symogih#6]
## Importation des acteurs
- E21 Person
- Dans projet 6857901

### Association à un projet
- cf. Semantic-Data-for-Humanities/Alignement_symogih.org#176
- associate_project.fk_collective_actor [associate_project.fk_object = actor.concat_actr]

12114	"Tiers-Ordre régulier de Saint-François"
12781	"Sippaf"
12782	"Scholasticon"
13250	"Mosare"
13683	"Arrash"
13691	"Couvent Saint Louis"
14136	"Evolution historique des territoires"
14158	"Histoire intellectuelle dans l'Europe moderne"
14411	"Privilèges (projet ANR)"
14545	"Géocatalogue Géo-larhra"
14632	"Livres de piété"
14638	"SIG Avesnois -CR du Nord-Pas-de-Calais"
14662	"Pôle histoire numérique (LARHRA)"
14679	"Groupe du Pôle Histoire Numérique sur le Web de données [à identifier]"
14698	"Monastica"
14829	"Edition du journal de Léonard Michon (1715-1743)"
14841	"Siprojuris"
15644	"Projet correspondance Déléage (1914-1918)"
15646	"LODOCAT"
15753	"Society Religion Science (SRS). Digital intellectual history"
15788	"""Zone"" de Paris"
15789	"Etablissements d'enseignement technique"
15912	"Réfugiés huguenots du Dauphiné"
15960	"Correspondance de Jacob Spon (1647-1685)"
16631	"Récits d'émigration du clergé français "
16959	"Réformation et votation"
20890	"Théèse forêts et sociétés"
21223	"Phonobase"
21341	"Recensement forestier de Despine"
21357	"Cimetières et sépultures en France"
21753	"Les représentations iconographiques des territoires de montagne aux XVIe et XVIIe siècles"

- Associer tous les acteurs et leurs informations liées au projet GV symogih 6857901.
- Associer les acteurs et leurs informations liées du projet symogih Siprojuris 14841 au projet GV Siprojuris 7918384
- Associer les acteurs et leurs informations liées du projet symogih Siprojuris 14841 au projet GV Academic Education & Careers (Community Project) 1483135
- Associer les acteurs et leurs informations liées du projet symogih Monastica 14698 au projet GV Monastica 801348
- Associer les acteurs et leurs informations liées du projet symogih Établissements d'enseignement technique 15789 au projet GV Établissements d'enseignement technique 8381499

### Créateur
- admin_users.login [actor.creator = admin_users.pk_user]

### Modificateur
- admin_users.login [actor.modifier = admin_users.pk_user]

### Appellations

- cf. Semantic-Data-for-Humanities/Alignement_symogih.org#161
- Noms des acteurs : actor_name.concat_name
- Type du nom : abstact_object.concat_standard_name [actor_name.fk_abob_name_type = pk_abstract_object]
- Temporalité : actor_name.begin... / end...
- Langue : actor_name.lang_iso [défaut fra]

### URI
- symogih.org/resource/ActrXXX

### Genre
- actor.gender_iso

### Notices textes
- cf. Semantic-Data-for-Humanities/Alignement_symogih.org#167
- Définition :
  - cas 1 : actor_text_property.text [actor_text_property.property_type = notice_web OR notice]
  - cas 2 : actor_text_property.text [actor_text_property.property_type = complément], à faire précéder de "[complément] "
  - cas 3 : actor.notes, à faire précéder de "[notes] "
- Langue : actor_text_property.lang_iso_code [défaut fra]

### Date de naissance
- On crée une entité "Birth" toutes les fois qu'on a soit une information naissance soit une année de naissance.
- Pour trouver la naissance : actor.pk_actor = information_role.fk_associated_object WHERE fk_type_role = 40
- Si information naissance, date de naissance : information_role.fk_information = information_date.fk_information
- sameAs URI : http://symogih.org/resource/InfoXXX [XXX = fk_information]

### Date de décès
- On crée une entité "Death" toutes les fois qu'on a soit une information décès soit une année de décès.
- Pour trouver la naissance : actor.pk_actor = information_role.fk_associated_object WHERE fk_type_role = 45
- Si information naissance, date de décès : information_role.fk_information = information_date.fk_information
- sameAs URI : http://symogih.org/resource/InfoXXX [XXX = fk_information]

#### Type de date
- Pour des événements de type naissance ou décès, la date est considérée comme "unique", c'est à dire qu'elle n'a pas de date de début ni de date de fin. Dans la BHP, il y a néanmoins plusieurs possibilités :
  - La plus simple, une date unique, information_date.fk_abob_type_information_date = 246 : P82 at some time within
  - Dans les cas où l'utilisateur ne connait pas exactement la date de l'information mais uniquement la période dans laquelle elle a pu se dérouler, il peut préciser un intervalle de dates dans lequel il sait que l'événement a eu lieu. Cet intervalle est composé d'une "date unique (à partir de, inclus)", information_date.fk_abob_type_information_date = 1125, et d'une "date unique (jusqu'à, inclus)", information_date.fk_abob_type_information_date = 1126.
    - 1125 : P82a begin of the begin
    - 1126 : P82b end of the end
- Si d'autres types de date ont été utilisés pour les naissance et les décès, ils l'ont été par erreur. Les signaler le cas échéant.
#### Indication de fiabilité
- Dans la BHP, il est possible aussi de préciser la fiabilité de la date, ce qui n'est pas possible dans GV. Si elle est exacte, aucun problème. Si elle est postulée ou reconstituée, il faut garder la trace de cette précision en ajoutant un commentaire dans l'événement. Cf. https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments
  - TeEn geov:P19 has comment geov:C20 Comment avec pour valeur "Date reconstituée" (certainty_date = 2) ou "Date postulée" (certainty_date = 3).
  - Pour indiquer qu'il ne s'agit pas d'un commentaire sur l'entité temporelle mais bien sur la date de cette entité, ajouter un type "Commentaire sur la date" (id GV 7953586) comme valeur pour P22 has comment type.
#### Compléments et notes
- Dans la BHP, il est possible d'ajouter des compléments ou des notes sur les dates des entités temporelles, ce qui n'est pas possible dans GV. Il faut pouvoir cependant conserver cette information en ajoutant un commentaire dans l'événement. Ces données se trouvent dans les colonnes information_date.complement, information_date.notes et information_date.date_hour_label.
  - cas 1 : information_date.complement et information_date.date_hour_label
    - TeEn geov:P19 has comment geov:C20 Comment geov:P22 has comment type "Compléments sur la date" (id GV 8065621).
  - cas 2 : information_date.notes
    - TeEn geov:P19 has comment geov:C20 Comment geov:P22 has comment type "Notes sur la date" (id GV 8065632).
### Notices d'autorité
- cf. Semantic-Data-for-Humanities/Alignement_symogih.org#167
- URI de l'autorité : resource_address.uri | documentation.identifier
- Avec :
  - documentation.fk_documented_object = objet de départ
  - documentation.fk_documenting_entity = objet numérique correspondant à l'institution qui attribue l'autorité
  - documentation.identifier = l'identifiant dans le système d'autorité
  - resource_adress_concatenation.fk_digital_object = documentation.fk_documenting_entity [moins DiOb...]
  - resource_adress_conactenation.fk_resource_address = resource_adress.pk_ressource_adress

**Comment by gaetanmuck** [comment]
Quelles sont les propriétés de début/fin pour une *Person Appellation In a Language*?

**Comment by stephenhart8** [comment]
Il me semble que c'est comme pour toute propriété temporelle? Avec le Time-Span et ensuite P81 et P82:
https://ontome.net/class/50/namespace/1

Par contre comme GV n'utilise pas de la même manière les time-span, je ne suis pas sûr de ce que j'avance

**Comment by gaetanmuck** [comment]
Autre question, j'ai aussi besoin de savoir ou trouver les Birth et les Death dans la BHP, malheureusement je n'y suis pas parvenu tout seul

**Comment by gaetanmuck** [comment]
Pour les noms qui n'ont pas de langue, je mets "Français" par défaut?

**Comment by gaetanmuck** [comment]
Pour les genres, je propose de mettre les entités:
- Male: pk = 739340
- Female: pk = 739346

Est ce que vous êtes d'accord?

**Comment by stephenhart8** [comment]
Pour répondre à tes deux questions:
- Je mettrais effectivement Français par défaut comme langue, vu que le projet est exclusivement francophone. Idem pour ls définitions
- Pour ce qui est des entités, après une [recherche rapide sur sparklis](https://sparklis.geovistory.org/?title=Geovistory%20Communtiy%20Data&endpoint=https%3A//sparql.geovistory.org/api_v1_community_data&sparklis-query=%5BVId%5DReturn%28Det%28An%288%2CModif%28Select%2CUnordered%29%2CClass%28%22https%3A//ontome.net/ontology/c629%22%29%29%2CNone%29%29&sparklis-path=D&entity_lexicon_select=http%3A//www.w3.org/2000/01/rdf-schema%23label&concept_lexicons_select=http%3A//www.w3.org/2000/01/rdf-schema%23label), il y a beaucoup d'instances de Male et Female. Je choisirais l'instance la plus utilisée (mais je ne sais pas comment faire pour trouver cette information)

**Comment by gaetanmuck** [comment]
Ok, merci pour vos réponse, je vais vérifier, mais les id que j'ai mis, je crois bien que c'set les plus fréquents.

**Comment by gaetanmuck** [comment]
Les noms des acteurs doivent être mis sous la forme "Nom, Prénom", comme dans Symogih?

**Comment by valamercery** [comment]
J'ai mis à jour le ticket (toujours en cours de rédaction). À mon avis, le plus simple est d'utiliser la colonne actor_name.concat_name

**Comment by gaetanmuck** [comment]
Que signifie "Si date postulée ou reconstituée" pour les naissances?

**Comment by gaetanmuck** [comment]
Autre point, je trouve dans Symogih, uniquement 11 Acteurs avec une naissance, est ce que cela vous semble cohérent?

```
    select 
        ir.fk_associated_object as pk_bhp
        ,ir.fk_information as fk_info
        ,id.year, id.month, id.day
    from bhp.information_role ir
    inner join bhp.information_date id on ir.fk_information = id.fk_information
    where 
        ir.fk_type_role = 41
    and ir.fk_associated_object ilike 'Actr%'
```

**Comment by gaetanmuck** [comment]
Est ce qu'il n'y aurait-il pas des erreurs en ce qui concerne les types de role:
- fk_type_role = 41 ==> délivrer
- fk_type_role = 81 ==> acquitter (vie économique)

Les URIs ne pointent pas vers des naissances/morts

**Comment by stephenhart8** [comment]
> Je fais face à un problème: Une personne existe sur Geovistory, avec une naissance et une date de naissance. Mais cette date est différente de celle sur Symogih. Une personne ne peut avoir qu'une seule naissance et qu'une naissance ne peut avoir qu'une seule date. Comment gérer les cas dont les personnes ont déjà une naissance sur Geovistory?
> 
> Proposition: Ignorer la date de Geovistory (pour le projet Symogih) et ajouter toujours la date de Symogih (si elle existe)

+1 pour ignorer la date dans Geovistory, lorsque l'on est dans le projet Symogih

**Comment by gaetanmuck** [comment]
Pour les associations à un projet, est ce que je comprends bien: on va créer un projet Geovistory pour chaque projet listé tout en haut?
Est ce qu'ils sont déjà créé? Si oui est-til possible d'avoir la correspondance des projets Geovistory?

**Comment by valamercery** [comment]
> Est ce qu'il n'y aurait-il pas des erreurs en ce qui concerne les types de role:
> 
>     * fk_type_role = 41 ==> délivrer
> 
>     * fk_type_role = 81 ==> acquitter (vie économique)
> 
> 
> Les URIs ne pointent pas vers des naissances/morts

En effet, il y a un problème et c'est de ma faute, désolé, j'ai interverti deux colonnes :(
Les bons rôles sont :
  * fk_type_role = 40 ==> naître
  * fk_type_role = 45 ==> mourir
Je corrige l'issue.

**Comment by valamercery** [comment]
> Que signifie "Si date postulée ou reconstituée" pour les naissances?

Cf. https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments, colonne certainty_date

**Comment by valamercery** [comment]
> Pour les associations à un projet, est ce que je comprends bien : on va créer un projet Geovistory pour chaque projet listé tout en haut? Est ce qu'ils sont déjà créés? Si oui est-til possible d'avoir la correspondance des projets Geovistory?

C'est le principe, en plus d'associer toutes les données importées au projet GV symogih. Mais on ne va pas tout de suite créer tous les projets. Il faudrait que tu puisses garder cette information quelque part dans GV pour pouvoir associer les données une fois que les projets seront créés.

Dans l'immédiat, nous avons décidé d'ajouter les données du projet Siprojuris (symogih 14841) à son propre projet GV (7918384) ainsi qu'au projet Academic Education & Careers (Curated Project) (GV 2164872).

Pour info à tous, il existe un autre projet actif dans GV, Monastica, mais je pense qu'il est préférable d'attendre un peu avant d'associer les données symogih à ce projet GV.

**Comment by gaetanmuck** [comment]
J'ai une question, est ce que ça pose problème qu'une personne a une date (naissance ou mort) unique (car sur la page principale de la BHP il y a une "date raccourcie") ET un intervalle de date?
Par exemple Lyonnet, Charles (pkbhp=11603) a une date de naissance dans sa fiche (1816), qui est donc déjà créée sur Geovistory, mais dans la BHP, il y a un intervalle également. Que faire?

**Comment by valamercery** [comment]
Je vais le préciser plus haut, si une information naissance ou décès existent, celles-ci sont prioritaires et il on ne prend pas en compte les années indiquées dans la fiche de l'acteur. Dans l'exemple de Lyonnet, il faut donc créer une Birth avec un intervalle de date.

**Comment by valamercery** [comment]
Les commentaires sur les dates ont été importés comme des C16 et non des C20. L'utilisation de la classe C20 a été précisée dans l'issue.
Il faut corriger les données ainsi :
crm:E1 geov:P19 geov:C16 en crm:E1 geov:P19 geov:C20
et
geov:C16 geov:P21 geov:C24 [instance 7953586 "commentaire sur la date"] en geov:C20 geov:P22 geov:C24
cf. https://ontome.net/profile/97#properties

**Comment by gaetanmuck** [comment]
Derniers éléments importés/corrigés,
Transfers dans les projets réalisés
