### ISSUE TITLE
Des acteurs sont mort avant d'être nés

### ISSUE THREAD

**Issue by gaetanmuck** [geovistory/symogih#7]
Des données ont été importées depuis la BHP avec une date de mort antérieure à la date de naissance, voici la liste: [fichier CSV](https://github.com/geovistory/symogih/blob/master/reports/death-before-birth.csv)

**Comment by valamercery** [comment]
Malheureusement, ce sont des données sales que nous ne pourrons pas corriger dans le cadre de cette importation.
