### ISSUE TITLE
Actors - Name complements

### ISSUE THREAD

**Issue by valamercery** [geovistory/symogih#9]
Les noms des acteurs de la BHP peuvent être typés et datés.

- Importer les données manquantes ci-dessous et les associer aux projets concernés (cf. #6 et #13  ).

## Types de noms

Cf. partie "acteurs" de https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#type-de-nom

## Noms standards

cf. https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#nom-standard

## Dates des noms

Cf. https://github.com/geovistory/symogih/wiki/Compl%C3%A9ments#temporalit%C3%A9-des-noms

**Comment by gaetanmuck** [comment]
Que fait-on des types vides?

**Comment by valamercery** [comment]
Si le type n'est pas renseigné dans symogih, alors on ne type pas non plus l'appellation dans GV.
